export default function Recruiters() {
  return (
    <section id="recruiters" style={{ padding: '120px 6vw 60px', position: 'relative', overflow: 'clip' }}>
      <div data-reveal className="mono" style={{ fontSize: '12px', letterSpacing: '.16em', textTransform: 'uppercase', color: '#7c3aed' }}>For recruiters</div>
      <h2 data-reveal data-d="1" className="serif" style={{ fontSize: 'clamp(40px,6.2vw,90px)', lineHeight: '1.0', letterSpacing: '-.02em', margin: '14px 0 0' }}>Hear the signal,<br /><span style={{ fontStyle: 'italic' }}>before the résumé.</span></h2>
      <p data-reveal data-d="2" style={{ fontSize: 'clamp(15px,1.6vw,19px)', color: '#5b576f', margin: '22px 0 0', maxWidth: '54ch', lineHeight: '1.55' }}>Discover candidates by demonstrated ability, ranked by how their interview signal fits the role, with the exact gap to close. Scroll the shortlist ↓</p>
      <div style={{ position: 'relative', marginTop: '48px' }}>
        <div className="dossier" style={{ position: 'sticky', top: '100px', background: '#fff', border: '1.5px solid rgba(124,58,237,.16)', borderRadius: '24px', padding: '30px', boxShadow: '0 40px 80px -50px rgba(40,20,90,.6)', display: 'grid', gridTemplateColumns: 'auto 1fr auto', gap: '28px', alignItems: 'center', marginBottom: '26px' }}>
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '10px' }}><span style={{ width: '64px', height: '64px', borderRadius: '16px', background: 'linear-gradient(135deg,#7c3aed,#3f1d80)', color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: '700', fontSize: '20px' }}>SK</span><span className="mono" style={{ fontSize: '9.5px', color: '#9591a8' }}>TECH LEAD</span></div>
          <div><div className="serif" style={{ fontSize: '34px', lineHeight: '1' }}>Sara K.</div><p style={{ fontSize: '14px', color: '#5b576f', margin: '8px 0 0', maxWidth: '44ch', lineHeight: '1.5' }}>Top-decile on Substance and Structure. Closed every system-design follow-up un-assisted.</p><svg viewBox="0 0 600 60" preserveAspectRatio="none" style={{ width: '100%', maxWidth: '420px', height: '42px', marginTop: '12px', overflow: 'hidden', WebkitMaskImage: 'linear-gradient(90deg,transparent,#000 14%,#000 86%,transparent)', maskImage: 'linear-gradient(90deg,transparent,#000 14%,#000 86%,transparent)' }}><g style={{ animation: 'flow 4s linear infinite' }}><path d="M0,30 C75,6 150,54 225,30 S375,4 450,30 S600,54 675,30 825,30" fill="none" stroke="#6366f1" strokeWidth="2.5" strokeLinecap="round" /></g></svg></div>
          <div className="dossier-right" style={{ textAlign: 'right' }}><div style={{ fontSize: '46px', fontWeight: '800', color: '#16a34a', lineHeight: '.9' }}>98<span style={{ fontSize: '15px', color: '#9591a8', fontWeight: '500' }}> fit</span></div><div className="dossier-chips" style={{ marginTop: '8px', display: 'flex', gap: '6px', justifyContent: 'flex-end' }}><span style={{ background: 'rgba(95,156,11,.14)', color: '#4d7c0f', fontWeight: '800', fontSize: '12px', borderRadius: '7px', padding: '4px 9px' }}>A+</span><span className="mono" style={{ fontSize: '12px', color: '#6366f1', fontWeight: '600', border: '1px solid #e3e1ee', borderRadius: '7px', padding: '4px 9px' }}>Technical 88</span></div></div>
        </div>
        <div className="dossier" style={{ position: 'sticky', top: '120px', background: '#fff', border: '1.5px solid #7c3aed', borderRadius: '24px', padding: '30px', boxShadow: '0 40px 80px -44px rgba(124,58,237,.6)', display: 'grid', gridTemplateColumns: 'auto 1fr auto', gap: '28px', alignItems: 'center', marginBottom: '26px' }}>
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '10px' }}><span style={{ width: '64px', height: '64px', borderRadius: '16px', background: 'linear-gradient(135deg,#d97706,#92400e)', color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: '700', fontSize: '20px' }}>MA</span><span className="mono" style={{ fontSize: '9.5px', color: '#9591a8' }}>OWNERSHIP</span></div>
          <div><div className="serif" style={{ fontSize: '34px', lineHeight: '1' }}>Maya A.</div><p style={{ fontSize: '14px', color: '#5b576f', margin: '8px 0 0', maxWidth: '44ch', lineHeight: '1.5' }}>Strongest Composure in the pool, recovered cleanly on every curveball, never froze.</p><svg viewBox="0 0 600 60" preserveAspectRatio="none" style={{ width: '100%', maxWidth: '420px', height: '42px', marginTop: '12px', overflow: 'hidden', WebkitMaskImage: 'linear-gradient(90deg,transparent,#000 14%,#000 86%,transparent)', maskImage: 'linear-gradient(90deg,transparent,#000 14%,#000 86%,transparent)' }}><g style={{ animation: 'flow 3.4s linear infinite' }}><path d="M0,30 C75,10 150,50 225,30 S375,2 450,30 S600,50 675,30 825,30" fill="none" stroke="#d97706" strokeWidth="2.5" strokeLinecap="round" /></g></svg></div>
          <div className="dossier-right" style={{ textAlign: 'right' }}><div style={{ fontSize: '46px', fontWeight: '800', color: '#16a34a', lineHeight: '.9' }}>95<span style={{ fontSize: '15px', color: '#9591a8', fontWeight: '500' }}> fit</span></div><div className="dossier-chips" style={{ marginTop: '8px', display: 'flex', gap: '6px', justifyContent: 'flex-end' }}><span style={{ background: 'rgba(124,58,237,.14)', color: '#7c3aed', fontWeight: '800', fontSize: '12px', borderRadius: '7px', padding: '4px 9px' }}>A</span><span className="mono" style={{ fontSize: '12px', color: '#d97706', fontWeight: '600', border: '1px solid #e3e1ee', borderRadius: '7px', padding: '4px 9px' }}>Behavioral 86</span></div></div>
        </div>
        <div className="dossier" style={{ position: 'sticky', top: '140px', background: '#fff', border: '1.5px solid rgba(14,165,233,.22)', borderRadius: '24px', padding: '30px', boxShadow: '0 40px 80px -50px rgba(40,20,90,.55)', display: 'grid', gridTemplateColumns: 'auto 1fr auto', gap: '28px', alignItems: 'center' }}>
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '10px' }}><span style={{ width: '64px', height: '64px', borderRadius: '16px', background: 'linear-gradient(135deg,#0ea5e9,#075985)', color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: '700', fontSize: '20px' }}>LZ</span><span className="mono" style={{ fontSize: '9.5px', color: '#9591a8' }}>STRUCTURED</span></div>
          <div><div className="serif" style={{ fontSize: '34px', lineHeight: '1' }}>Lin Z.</div><p style={{ fontSize: '14px', color: '#5b576f', margin: '8px 0 0', maxWidth: '44ch', lineHeight: '1.5' }}>Cleanest Clarity score on record, premise to payoff with zero backtracking.</p><svg viewBox="0 0 600 60" preserveAspectRatio="none" style={{ width: '100%', maxWidth: '420px', height: '42px', marginTop: '12px', overflow: 'hidden', WebkitMaskImage: 'linear-gradient(90deg,transparent,#000 14%,#000 86%,transparent)', maskImage: 'linear-gradient(90deg,transparent,#000 14%,#000 86%,transparent)' }}><g style={{ animation: 'flow 4.6s linear infinite' }}><path d="M0,30 C75,16 150,44 225,30 S375,12 450,30 S600,44 675,30 825,30" fill="none" stroke="#0ea5e9" strokeWidth="2.5" strokeLinecap="round" /></g></svg></div>
          <div className="dossier-right" style={{ textAlign: 'right' }}><div style={{ fontSize: '46px', fontWeight: '800', color: '#16a34a', lineHeight: '.9' }}>91<span style={{ fontSize: '15px', color: '#9591a8', fontWeight: '500' }}> fit</span></div><div className="dossier-chips" style={{ marginTop: '8px', display: 'flex', gap: '6px', justifyContent: 'flex-end' }}><span style={{ background: 'rgba(124,58,237,.14)', color: '#7c3aed', fontWeight: '800', fontSize: '12px', borderRadius: '7px', padding: '4px 9px' }}>A</span><span className="mono" style={{ fontSize: '12px', color: '#0ea5e9', fontWeight: '600', border: '1px solid #e3e1ee', borderRadius: '7px', padding: '4px 9px' }}>Reasoning 83</span></div></div>
        </div>
      </div>
    </section>
  );
}
